// Todos os textos visíveis do Forgia, em português do Brasil.
// Outro idioma = outro arquivo com as mesmas chaves. Aqui só entram dados e funções de
// formatação puras (texto com valor vira função).

export default {
  app: {
    nome: 'Forgia',
    titulo: 'Forgia — Editor 3D para impressão',
    // título da janela: nome do arquivo (ou do projeto ainda sem arquivo) e "•" com alteração não salva
    tituloJanela: (nome, sujo) => `${nome}${sujo ? ' •' : ''} — Forgia`,
  },

  // barra superior e controles do canto inferior direito
  barra: {
    novo: 'Novo projeto',
    arquivo: 'Arquivo',
    importar: 'Importar',
    exportar: 'Exportar',
    atalhos: 'Atalhos',
    temaEscuro: 'Mudar para o tema escuro',
    temaClaro: 'Mudar para o tema claro',
    configuracoes: 'Configurações',
    area: 'Área',
    areas: {
      padrao: '255³ (padrão)',
      bambu: '256³ Bambu A1/P1',
      a1mini: '180³ A1 mini',
      prusa: '250×210×220 Prusa',
      ender3: '220×220×250 Ender 3',
      grande: '300³ grande',
    },
    areaMedidas: (w, l, h) => `${w}×${l}×${h}`,
    areaPersonalizada: 'Personalizado…',
    ajustarGrade: 'Ajustar grade',
    gradeDesligada: 'Desligado',
    grade: (mm) => `${mm.toLocaleString('pt-BR', { minimumFractionDigits: 1 })} mm`,
  },

  // barra de ferramentas (aria-label; chave = data-cmd)
  ferramentas: {
    copy: 'Copiar (Ctrl+C)',
    paste: 'Colar (Ctrl+V)',
    duplicate: 'Duplicar e repetir (Ctrl+D)',
    delete: 'Excluir (Delete)',
    undo: 'Desfazer (Ctrl+Z)',
    redo: 'Refazer (Ctrl+Y)',
    showAll: 'Mostrar tudo (Ctrl+Shift+H)',
    group: 'Agrupar (Ctrl+G)',
    ungroup: 'Desagrupar (Ctrl+Shift+G)',
    align: 'Alinhar (L)',
    mirror: 'Espelhar (M)',
    draw: 'Desenhar (B)',
    cruise: 'Cruzeiro (C)',
    measure: 'Medir (R)',
    mark: 'Marcar parte (N)',
    encaixe: 'Criar encaixe',
    workplane: 'Plano de trabalho (P)',
  },

  // Criar encaixe (src/encaixe.js): diálogo, nomes do resultado e aviso
  encaixe: {
    titulo: 'Criar encaixe',
    explica: 'Cria, ao lado da peça, um bloco com o negativo dela, aberto em cima, para imprimir um soquete ou suporte onde ela entra. O resultado é um grupo editável.',
    folga: 'Folga (mm)',
    folgaAjuda: 'Espaço entre a peça e o encaixe, em cada lado. 0,25 mm costuma entrar sem apertar.',
    margem: 'Parede do bloco (mm)',
    criar: 'Criar encaixe',
    grupo: (nome) => `Encaixe de ${nome}`,
    bloco: 'Bloco',
    copia: (nome) => `${nome} (folga)`,
    feito: (folga) => `Encaixe criado com folga de ${folga} mm.`,
    aproximada: 'Encaixe criado, mas a folga é aproximada nesta peça (faces curvas ou em contorno, texto ou malha importada): confira com Medir.',
  },

  // coluna de navegação (aria-label; chave = data-view) e faces do cubo
  vista: {
    home: 'Vista inicial',
    fit: 'Ajustar à tela (F)',
    in: 'Aproximar',
    out: 'Afastar',
    ortho: 'Vista ortográfica / perspectiva',
    // gabarito discreto com a vista afastada (src/gabarito.js): [teclas ('+' é só o sinal), ação]
    gabarito: [
      [['Botão direito', '+', 'arrastar'], 'Girar a vista'],
      [['W', 'A', 'S', 'D'], 'Andar pela mesa'],
      [['Roda do mouse'], 'Aproximar / afastar'],
    ],
    // ordem dos materiais da BoxGeometry: +X, −X, +Y, −Y, +Z, −Z
    cubo: ['DIREITA', 'ESQUERDA', 'SUPERIOR', 'INFERIOR', 'FRENTE', 'TRÁS'],
  },

  biblioteca: {
    titulo: 'Biblioteca',
    basicas: 'Formas básicas',
    letras: 'Letras e números',
    pesquisar: 'Pesquisar',
    nenhuma: 'Nenhuma forma encontrada',
    // categorias (chave = src/biblioteca.js CATEGORY_ORDER)
    categorias: {
      criacoes: 'Suas criações',
      favoritos: 'Favoritos',
      basic: 'Formas básicas',
      letters: 'Letras e números',
      iniciantes: 'Iniciantes do projeto',
      hardware: 'Hardware',
      geradores: 'Geradores de forma',
    },
    iniciantes: {
      chaveiro: 'Chaveiro com nome',
      suporteCelular: 'Suporte de celular',
      caixaComTampa: 'Caixa com tampa',
      bonecoDeNeve: 'Boneco de neve',
      foguete: 'Foguete',
    },
    favoritar: 'Marcar como favorito',
    desfavoritar: 'Tirar dos favoritos',
    semFavoritos: 'Nenhum favorito ainda. Passe o mouse sobre uma forma e clique na estrela.',
    semCriacoes: 'Nenhuma criação ainda. Selecione uma peça sua e clique em "Salvar seleção como criação".',
    salvarCriacao: 'Salvar seleção como criação',
    salvarCriacaoExplica: 'A seleção vira uma forma da biblioteca, em Suas criações, para usar de novo em qualquer projeto. Fica guardada neste computador.',
    nomeCriacao: 'Nome',
    criacaoPadrao: 'Minha criação',
    salvar: 'Salvar',
    criacaoSalva: (nome) => `"${nome}" está em Suas criações.`,
    criacaoNaoSalva: 'Não foi possível salvar a criação.',
    renomearCriacao: 'Renomear criação',
    renomear: 'Renomear',
    excluirCriacao: 'Excluir criação',
    excluirCriacaoTexto: (nome) => `Excluir "${nome}" de Suas criações? As peças já usadas nos projetos continuam lá.`,
    excluir: 'Excluir',
  },

  // painel lateral: abas Biblioteca | Objetos
  painel: {
    rotulo: 'Painel lateral',
    biblioteca: 'Biblioteca',
    objetos: 'Objetos',
  },

  // lista de objetos (src/lista.js): árvore do projeto, com grupos, ocultos e bloqueados
  lista: {
    vazia: 'Nenhum objeto ainda. Arraste uma forma da biblioteca para a mesa.',
    ocultar: 'Ocultar',
    mostrar: 'Mostrar',
    bloquear: 'Bloquear',
    desbloquear: 'Desbloquear',
    abrirGrupo: 'Mostrar as partes',
    fecharGrupo: 'Esconder as partes',
    renomear: 'Nome do objeto',
    furo: 'furo',
    partes: (n) => `${n} ${n === 1 ? 'parte' : 'partes'}`,
    ultimaParte: 'Essa é a última parte visível do grupo: oculte o grupo inteiro.',
  },

  // projeto em arquivo (.forgia, src/arquivo.js): menu Arquivo, diálogos e perguntas
  arquivo: {
    abrir: 'Abrir…',
    salvar: 'Salvar',
    salvarComo: 'Salvar como…',
    recentes: 'Recentes',
    semRecentes: 'Nenhum projeto recente',
    naoEncontrado: 'não encontrado',
    dialogoSalvar: 'Salvar projeto do Forgia',
    dialogoAbrir: 'Abrir projeto do Forgia',
    filtro: 'Projeto do Forgia (.forgia)',
    // ao lado do nome do projeto: arquivo e "•" com alteração não salva
    semArquivo: 'não salvo em arquivo',
    salvo: (nome) => `Salvo em ${nome}`,
    naoSalvou: (nome, motivo) => `Não foi possível salvar ${nome}${motivo ? ': ' + motivo : ''}`,
    naoAbriu: (nome, motivo) => `Não foi possível abrir ${nome}${motivo ? ': ' + motivo : ''}`,
    malhasFaltando: (n) => `${n} ${n === 1 ? 'malha importada não estava' : 'malhas importadas não estavam'} no arquivo e ${n === 1 ? 'aparece' : 'aparecem'} como caixa.`,
    motivos: {
      zip: 'o arquivo está danificado',
      formato: 'não é um projeto do Forgia',
      versao: 'foi salvo por uma versão mais nova do Forgia; atualize o programa',
      dados: 'o projeto dentro do arquivo está incompleto',
      naoEncontrado: 'o arquivo não foi encontrado',
      grande: 'o arquivo passa de 1 GB',
      gravar: 'sem permissão para gravar nessa pasta',
    },
    pergunta: {
      titulo: 'Salvar as alterações?',
      arquivo: (nome) => `Há alterações não salvas em ${nome}. Salvar antes de continuar?`,
      trocarNovo: (nome) => `O projeto "${nome}" ainda não foi salvo em arquivo. Salvar antes de continuar? Se não salvar, ele será apagado deste computador.`,
      fecharNovo: (nome) => `O projeto "${nome}" ainda não foi salvo em arquivo. Salvar agora? Se não salvar, ele continua aqui na próxima vez que você abrir o Forgia.`,
      salvar: 'Salvar',
      naoSalvar: 'Não salvar',
      cancelar: 'Cancelar',
    },
    recuperar: {
      titulo: 'Recuperar alterações?',
      texto: (nome, quando) => `Há alterações não salvas de ${nome}${quando ? ` (${quando})` : ''}. Recuperar?`,
      recuperar: 'Recuperar',
      descartar: 'Descartar',
      abrirOutro: (nome) => `Descartar e abrir ${nome}`,
    },
  },

  formas: {
    // chave = tipo da forma em shapes.js
    nomes: {
      box: 'Caixa',
      cylinder: 'Cilindro',
      sphere: 'Esfera',
      roof: 'Telhado',
      cone: 'Cone',
      roundRoof: 'Telhado redondo',
      text: 'Texto',
      wedge: 'Cunha',
      pyramid: 'Pirâmide',
      halfSphere: 'Meia esfera',
      polygon: 'Polígono',
      paraboloid: 'Paraboloide',
      torus: 'Toroide',
      tube: 'Tubo',
      star: 'Estrela',
      heart: 'Coração',
      icosahedron: 'Icosaedro',
      mesh: 'Importado',
      desenho: 'Desenho',
      // Hardware e Geradores de forma (src/geradores/)
      nut: 'Porca sextavada',
      bolt: 'Parafuso',
      boltHole: 'Furo para parafuso e porca',
      insertHole: 'Furo para inserto a quente',
      gear: 'Engrenagem',
      grid: 'Grade',
      spring: 'Mola',
      hinge: 'Dobradiça',
      curvedText: 'Texto curvo',
      lidBox: 'Caixa com tampa',
    },
    // rótulos dos parâmetros no inspetor (chave = parâmetro)
    params: {
      radius: 'Raio',
      steps: 'Passos',
      sides: 'Lados',
      bevel: 'Chanfro',
      top: 'Raio superior',
      text: 'Texto',
      tube: 'Espessura',
      wall: 'Espessura da parede',
      points: 'Pontas',
      ratio: 'Raio interno',
      detail: 'Detalhe',
      // Hardware e Geradores
      m: 'Medida (M)',
      thread: 'Rosca',
      clearance: 'Folga',
      segments: 'Segmentos por volta',
      length: 'Comprimento',
      head: 'Cabeça',
      nut: 'Bolsão da porca',
      diameter: 'Diâmetro',
      depth: 'Profundidade',
      chamfer: 'Chanfro de entrada',
      module: 'Módulo',
      teeth: 'Dentes',
      thickness: 'Espessura',
      bore: 'Furo central',
      backlash: 'Folga entre dentes',
      resolution: 'Resolução do perfil',
      width: 'Largura',
      cell: 'Célula',
      border: 'Moldura',
      pattern: 'Padrão',
      wire: 'Diâmetro do fio',
      pitch: 'Passo',
      coils: 'Espiras',
      knuckles: 'Juntas',
      pin: 'Diâmetro do pino',
      arcRadius: 'Raio do arco',
      angle: 'Ângulo do arco',
      letterSize: 'Altura das letras',
      relief: 'Relevo',
      height: 'Altura (fechada)',
      floor: 'Fundo',
      lid: 'Espessura da tampa',
      lip: 'Altura da aba',
      part: 'Peças',
    },
    // rótulos das opções dos parâmetros de lista (chave = optionsKey do gerador; valor = número)
    opcoes: {
      m: { 2: 'M2', 2.5: 'M2.5', 3: 'M3', 4: 'M4', 5: 'M5', 6: 'M6', 8: 'M8' },
      thread: { 0: 'Lisa', 1: 'Real' },
      head: { 0: 'Cilíndrica (allen)', 1: 'Sextavada', 2: 'Sem rebaixo' },
      nut: { 0: 'Sem bolsão', 1: 'Com bolsão' },
      pattern: { 0: 'Colmeia', 1: 'Quadrado' },
      part: { 0: 'Caixa e tampa', 1: 'Só a caixa', 2: 'Só a tampa' },
    },
    // dica da peça no inspetor (Hardware e Geradores)
    dicas: {
      nut: 'Rosca real abaixo de M4 imprime mal em FDM: prefira inserto a quente ou rosca lisa com parafuso autoatarraxante.',
      bolt: 'Imprima em pé, com a cabeça na mesa. Rosca real abaixo de M4 imprime mal em FDM: prefira inserto a quente ou rosca lisa com parafuso autoatarraxante.',
      boltHole: 'Nasce como furo: agrupe com a peça. Deixe-o um pouco mais comprido que a peça para cortar limpo.',
      insertHole: 'Nasce como furo. Encoste o inserto com o ferro de solda e empurre reto; deixe parede em volta (M2 1,3; M3 1,6; M4 2,1 mm).',
      gear: 'Duas engrenagens do mesmo módulo engrenam com os centros a m × (z1 + z2) / 2.',
      grid: 'Colmeia leve e rígida para tampas, grades de ventilação e bases.',
      spring: 'Em FDM, imprima em pé com suporte; fio de pelo menos 1,2 mm.',
      hinge: 'Imprime já montada, deitada na mesa. Não use folga menor que 0,4 mm.',
      curvedText: 'Aumente o raio para um arco mais aberto; o ângulo espalha as letras pelo arco.',
      lidBox: 'Caixa e tampa saem lado a lado, prontas para imprimir; a aba entra com a folga por lado.',
    },
    // texto da forma Texto recém-criada (e quando o texto fica vazio)
    textoPadrao: 'TEXTO',
  },

  inspetor: {
    varias: (n) => `Formas (${n})`,
    // cabeçalhos de seção
    material: 'Material',
    parametros: 'Parâmetros',
    grupo: 'Grupo',
    bloquear: 'Bloquear (Ctrl+L)',
    desbloquear: 'Desbloquear (Ctrl+L)',
    ocultar: 'Ocultar (Ctrl+H)',
    soltar: 'Soltar na mesa (Shift+D)',
    recolher: 'Recolher',
    expandir: 'Expandir',
    solido: 'Sólido',
    furo: 'Furo',
    personalizado: 'Personalizado',
    multicolorido: 'Multicolorido',
    agrupadas: (n) => `${n} formas agrupadas`,
  },

  // dica na base da vista durante colocação e modos
  modos: {
    posicionar: 'Clique no plano de trabalho para posicionar a forma — Esc cancela',
    alinhar: 'Clique num dos pontos para alinhar. Clique numa forma selecionada para usá-la como referência.',
    espelhar: 'Clique numa seta para espelhar a seleção naquele eixo.',
    desenhar: 'Arraste para desenhar à mão livre ou clique para pôr pontos na grade. Enter ou o 1º ponto fecha — Esc cancela',
    cruzeiro: 'Arraste a bolinha verde para a peça deslizar pela superfície das outras. Shift afunda na face — Esc sai',
    marcar: 'Clique num ponto da peça para pôr um alfinete e escrever o pedido só daquela parte — Esc sai',
    marcarChat: 'Escreva o pedido e aperte Enter para copiá-lo com a imagem — Esc fecha',
    marcarChatEnviar: 'Escreva o pedido e aperte Enter para enviá-lo à IA — Esc fecha',
    plano: 'Clique numa face para ela virar o plano de trabalho, ou na mesa para voltar a ela — Esc cancela',
    // régua Medir, por etapa: nenhum ponto, só o inicial, os dois
    medir: {
      inicio: 'Clique no ponto inicial: ele gruda em vértice, meio de aresta, centro de furo, face e grade — Esc sai',
      fim: 'Clique no ponto final — Esc sai',
      pronto: 'Clique na distância para digitar outra e mover a peça do ponto final. Arraste os pontos para ajustar — Esc sai',
    },
  },

  editor: {
    nomePadrao: 'Meu projeto 3D',
    semTitulo: 'Sem título',
    grupo: 'Grupo',
    // title dos pontos de alinhar: início, centro e fim do eixo
    alinhar: ['Esquerda', 'Centro', 'Direita'],
    espelhar: 'Espelhar',
    // title da bolinha de arraste do Cruzeiro
    cruzeiro: 'Arraste para deslizar pela superfície',
    // régua Medir: rótulo da distância, diferenças por eixo (sistema Z para cima) e onde o ponto gruda
    // régua da mesa (src/regua.js): total na ponta e largura da faixa da seleção
    regua: {
      total: (v) => `${v} mm`,
      largura: (v) => `${v} mm`,
    },
    medir: {
      editar: 'Clique para digitar a distância',
      total: (v) => `${v} mm`,
      eixo: (eixo, v) => `${eixo} ${v}`,
      tipos: { vertice: 'vértice', aresta: 'meio da aresta', centro: 'centro', face: 'face', grade: 'grade' },
    },
  },

  dialogos: {
    cancelar: 'Cancelar',
    // botão X (aria-label) e botão redondo do vídeo do cartão de dica
    fechar: 'Fechar',
    video: { pausar: 'Pausar vídeo', tocar: 'Tocar vídeo' },
    exportar: {
      titulo: 'Exportar',
      tudo: 'Tudo no design',
      selecionadas: 'Formas selecionadas',
      impressao: 'Para impressão 3D',
      stl: '.STL',
      obj: '.OBJ',
      glb: '.GLB',
      tresmf: '.3MF (cores e peças separadas)',
      nota3mf: 'O .3MF leva cada peça separada e com a sua cor, pronta para imprimir em várias cores no Bambu Studio ou no OrcaSlicer.',
      nota: 'Furos não são exportados sozinhos: agrupe-os com um sólido para recortar.',
      // nome do arquivo quando o projeto não tem nome
      arquivo: 'projeto',
    },
    configuracoes: {
      titulo: 'Configurações',
      aparencia: 'Aparência',
      // chave = nome do tema em src/theme.js
      temas: { claro: 'Claro', escuro: 'Escuro' },
      plano: 'Plano de trabalho',
      largura: 'Largura (mm)',
      comprimento: 'Comprimento (mm)',
      altura: 'Altura (mm)',
      atualizar: 'Atualizar grade',
      ia: 'IA',
      permitirIA: 'Permitir IA (o agente de IA controla o Forgia pela ponte local)',
      permitirCodigo: 'Permitir código livre da IA (só quando nenhum comando pronto resolve)',
      conectar: 'Conectar IA…',
      versao: (v) => `Forgia v${v}`,
    },
    // Conectar IA: gera o texto para colar no agente (Fase C)
    conectar: {
      titulo: 'Conectar IA',
      copiar: 'Copiar',
      copiado: 'Copiado. Cole no seu agente.',
      fechar: 'Fechar',
    },
    atalhos: {
      titulo: 'Atalhos e controles',
      linhas: [
        ['Ctrl+S / Ctrl+Shift+S', 'Salvar / salvar como (.forgia)'],
        ['Ctrl+O', 'Abrir projeto (.forgia)'],
        ['Arrastar forma da biblioteca', 'Criar forma no plano'],
        ['Clique / Shift+clique', 'Selecionar / somar à seleção'],
        ['Arrastar no vazio', 'Seleção por área'],
        ['Botão direito + arrastar', 'Girar a vista'],
        ['Botão do meio / Shift+direito', 'Mover a vista'],
        ['Roda do mouse', 'Zoom'],
        ['W A S D', 'Andar pela mesa'],
        ['Alt + arrastar forma', 'Duplicar arrastando'],
        ['Shift nas alças', 'Manter proporção / girar de 45°'],
        ['Alt nas alças', 'Redimensionar a partir do centro'],
        ['Setas / Shift+setas', 'Mover na grade (×10)'],
        ['Ctrl + ↑ / ↓', 'Subir / descer'],
        ['Ctrl+C / Ctrl+V / Ctrl+D', 'Copiar / colar / duplicar e repetir'],
        ['Ctrl+Z / Ctrl+Y', 'Desfazer / refazer'],
        ['Ctrl+G / Ctrl+Shift+G', 'Agrupar / desagrupar'],
        ['W / A / S / D', 'Andar com a vista'],
        ['H / Shift+S', 'Furo / sólido'],
        ['Shift+D', 'Soltar no plano de trabalho'],
        ['Arrastar arquivo para a tela', 'Importar STL / OBJ / 3MF'],
        ['L / M', 'Alinhar / espelhar'],
        ['B', 'Desenhar na mesa (Enter fecha, Esc cancela)'],
        ['C', 'Cruzeiro: deslizar a peça pela superfície (Shift afunda)'],
        ['R', 'Medir: distância e X/Y/Z entre dois pontos'],
        ['N', 'Marcar parte: alfinete num ponto e pedido só daquela parte para a IA'],
        ['P', 'Plano de trabalho: uma face vira o chão (P de novo volta à mesa)'],
        ['F', 'Ajustar à tela'],
        ['Ctrl+L / Ctrl+H', 'Bloquear / ocultar'],
        ['Delete', 'Excluir'],
      ],
      // formato procurado pelos testes: "Placa de vídeo: <nome> (GPU|modo software)"
      placa: (nome, gpu) => `Placa de vídeo: ${nome || 'desconhecida'} (${gpu ? 'GPU' : 'modo software'})`,
    },
  },

  // barra de status (X/Y/Z no sistema do usuário: Z para cima, Y para o fundo)
  status: {
    semSelecao: 'Nada selecionado',
    centro: (x, y, z) => `X ${x}   Y ${y}   Z ${z}`,
    medidas: (x, y, z) => `${x} × ${y} × ${z} mm`,
    selecionadas: (n) => `${n} selecionadas`,
    rotuloCentro: 'Centro da seleção (mm)',
    conectar: 'Conectar IA',
    // com o plano de trabalho ativo, X/Y/Z e a elevação são relativos a ele
    plano: 'Plano de trabalho',
    // crédito na ponta direita (também no Sobre, no diálogo Atalhos)
    credito: 'por LarcherTech',
    creditoAria: 'LarcherTech — abre o site no navegador',
  },

  // ponte da IA: indicador, aviso do que a IA fez e Configurações
  ia: {
    estados: {
      conectada: 'IA conectada',
      pronta: 'IA pronta',
      desligada: 'IA desligada',
      indisponivel: 'IA indisponível',
    },
    aviso: (partes) => `IA: ${partes}`,
    codigo: (partes) => (partes ? `IA executou código: ${partes}` : 'IA executou código'),
    criou: (n) => `criou ${n}`,
    alterou: (n) => `alterou ${n}`,
    excluiu: (n) => `excluiu ${n}`,
    desfez: 'IA: desfez o último passo',
    refez: 'IA: refez o passo desfeito',
    desfazer: 'Desfazer',
  },

  // Marcar parte (src/marcar.js): mini-chat do alfinete e o pedido copiado para o agente
  marcar: {
    titulo: (n) => `Marcação ${n}`,
    placeholder: 'O que mudar nesta parte? Enter copia o pedido',
    // com a integração com o Agent Code ligada, Enter envia em vez de copiar
    placeholderEnviar: 'O que mudar nesta parte? Enter envia à IA',
    enviar: 'Enviar à IA',
    copiar: 'Copiar',
    excluir: 'Excluir marcador',
    limparN: (n) => `Limpar marcações (${n})`,
    copiado: 'Copiado. Cole no seu agente.',
    // balão que sai do alfinete
    balao: {
      copiado: 'Pedido copiado! Cole numa conversa com a sua IA (Claude, Codex…) para ela fazer.',
      trabalhando: 'A IA está trabalhando neste pedido…',
      terminou: (r) => (r ? `A IA terminou: ${r}` : 'A IA terminou de criar.'),
      erro: (e) => `A IA não conseguiu: ${e}`,
      cancelado: 'Pedido cancelado.',
    },
    naoCopiou: 'Não foi possível copiar para a área de transferência.',
    inclinada: (normal) => `inclinada (${normal})`,
    // "Marcação 1: Caixa 'aba' (parte de 'suporte'), ponto (12; −4; 30) mm, face virada para +X"
    referencia: ({ n, tipo, nome, furo, grupo, ponto, face }) =>
      `Marcação ${n}: ${furo ? 'furo ' : ''}${tipo} '${nome}'${grupo ? ` (parte de '${grupo}')` : ''}, ponto (${ponto}) mm, face virada para ${face}`,
    // pedido copiado: texto legível + bloco JSON estável (formato forgia.pedido/1)
    pedido: ({ referencia, texto, json }) =>
      [
        'Pedido feito no Forgia, só para a parte marcada (detalhes: forgia_marcacoes).',
        referencia + '.',
        `Pedido: ${texto && texto.trim() ? texto.trim() : '(sem texto)'}`,
        '',
        '```forgia-pedido',
        json,
        '```',
      ].join('\n'),
  },

  // integração com o Agent Code (src/agentcode.js, src/pedido-ia.js e a opção Agent Code do
  // Conectar IA, src/conectar.js)
  agentcode: {
    nome: 'Agent Code',
    oQueE: 'é um app para Windows, em português, que roda o Claude sem terminal. É da LarcherTech, a mesma do Forgia.',
    vantagem: 'Depois de integrar, é só escrever o que você quer em "Pedir à IA", na barra de baixo, ou clicar em Marcar, na conversa, marcar uma parte da peça e dizer o que mudar. A IA faz a peça aqui mesmo no Forgia: sem copiar e colar, sem trocar de janela.',
    exige: 'Você precisa do Agent Code aberto e de uma conta Claude com plano pago (Pro ou Max).',
    verPlanos: 'Ver os planos',
    baixar: 'Baixar o Agent Code (GitHub)',
    integrar: 'Integrar',
    desligar: 'Desligar integração',
    procurando: 'Procurando o Agent Code…',
    estados: {
      ausente: 'Agent Code não encontrado. Abra o Agent Code (ou baixe e instale) e clique em Integrar.',
      login: 'Abra o Agent Code e entre na sua conta Claude.',
      indisponivel: 'O Agent Code está aberto, mas ainda não está pronto. Tente de novo em instantes.',
      pronto: 'Agent Code encontrado. Clique em Integrar.',
      integrado: (v) => `Integrado${v ? ` (Agent Code ${v})` : ''}. Clique em "Pedir à IA", na barra de baixo, para conversar com a IA.`,
      integradoAusente: 'Integrado, mas o Agent Code não está aberto agora. Abra o Agent Code para pedir.',
      desligado: 'Integração desligada.',
    },
    erros: {
      ausente: 'Agent Code não encontrado: abra o Agent Code e tente de novo.',
      login: 'Abra o Agent Code e entre na sua conta Claude.',
      indisponivel: 'O Agent Code está aberto, mas ainda não está pronto. Tente de novo em instantes.',
      recusado: 'O Agent Code recusou o Forgia: atualize os dois apps.',
      rede: 'O Agent Code não respondeu. Tente de novo.',
      // o pedido pode ter chegado: o Forgia não reenvia para não fazer a peça duas vezes
      incerto: 'O Agent Code não confirmou o pedido. Veja no Agent Code se ele está sendo feito antes de pedir de novo.',
      erro: (m) => m || 'O Agent Code não conseguiu fazer o pedido.',
    },
    // botão "Pedir à IA" na barra de status e a conversa que sobe dele (src/pedido-ia.js)
    rotulo: 'Pedir à IA',
    rotuloTrabalhando: 'IA trabalhando…',
    conversa: 'Conversa com a IA',
    placeholder: 'Descreva a peça ou a mudança… Enter envia',
    enviarBtn: 'Enviar',
    vazio: 'Escreva o que quer (ex.: "faça um chaveiro com o nome ANA") ou use o Marcar, aqui em cima: clique nele e depois na parte da peça que a IA deve mudar.',
    vazioSemIntegracao: 'Use o Marcar, aqui em cima: clique nele, depois na parte da peça, escreva o pedido e copie para a sua IA.',
    marcarBtn: 'Marcar',
    convite: 'Peça para a IA: ela cria e muda as peças aqui no Forgia. Clique para começar.',
    semIntegracao: 'Para a IA fazer a peça aqui mesmo, sem copiar e colar, integre o Agent Code.',
    conectarBtn: 'Conectar IA',
    voce: 'Você',
    ia: 'IA',
    marcacao: (n) => `Marcação ${n}`,
    ocupado: 'A IA ainda está no pedido anterior. Espere ou cancele.',
    // painel da tarefa, no canto da vista
    status: { enviando: 'Enviando ao Agent Code…', na_fila: 'Na fila do Agent Code…', rodando: 'A IA está trabalhando…', concluida: 'Pronto', erro: 'Não deu certo', cancelada: 'Cancelado' },
    cancelando: 'Cancelando…',
    canceladoProjeto: 'Outro projeto foi aberto.',
    naoCancelou: 'Não deu para cancelar agora. Tente de novo ou cancele no Agent Code.',
    semResposta: 'O Agent Code não está respondendo; tentando de novo…',
    cancelar: 'Cancelar',
    fechar: 'Fechar',
  },

  // diálogo Conectar IA (src/conectar.js): um texto para colar no agente escolhido. Os pedaços
  // técnicos (comandos, JSON, TOML, com os caminhos desta instalação) vêm prontos de conectar.js
  conectar: {
    // dois parágrafos: o que fazer e o que o usuário precisa saber
    explica: [
      'Escolha o seu agente de IA, copie o texto e cole numa conversa com ele. O agente instala o servidor MCP do Forgia e, a partir daí, cria e muda as peças aqui mesmo.',
      'Você não instala mais nada: o servidor já vem com o Forgia. Atualizou o Forgia? Cole o texto de novo.',
    ],
    agente: 'Agente',
    agentes: { agentcode: 'Agent Code', claudecode: 'Claude', codex: 'Codex', cursor: 'Cursor', generico: 'Outro' },
    semPonte: 'A ponte da IA só existe no programa instalado (Forgia.exe).',
    ponteAtiva: (porta) => `Ponte ligada em 127.0.0.1:${porta}.`,
    ponteInativa: (erro) => `A ponte não está ligada${erro ? ': ' + erro : ''}.`,
    // p = { exe, script, env, claudeAdd, claudeJson, codexToml, cursorJson, genericoJson } (conectar.js)
    prompts: {
      claudecode: (p) =>
        [
          'Instale o servidor MCP do Forgia (o editor 3D aberto neste computador) e libere as ferramentas dele. Faça nesta ordem:',
          '',
          '1. Registre o servidor no escopo do usuário, para valer em qualquer pasta. Se já existir um servidor "forgia", ele é trocado pelo novo (o primeiro comando pode avisar que não existe: tudo bem):',
          '   claude mcp remove --scope user forgia',
          `   ${p.claudeAdd}`,
          '   Se o comando claude não existir aqui, edite ~/.claude.json e MESCLE em "mcpServers" (sem apagar os outros servidores) a entrada:',
          `   "forgia": ${p.claudeJson}`,
          '',
          '2. Libere as ferramentas sem pedido de permissão: em ~/.claude/settings.json, acrescente "mcp__forgia" à lista permissions.allow. MESCLE: leia o arquivo, mantenha tudo o que já existe (outras permissões, hooks, env, modelo…) e só inclua "mcp__forgia" se ainda não estiver lá. Se o arquivo não existir, crie com {"permissions":{"allow":["mcp__forgia"]}}. Confira que o JSON continua válido.',
          '',
          '3. Confirme: liste as ferramentas forgia_* e chame forgia_estado com o Forgia aberto. O MCP só carrega quando a conversa começa: se as ferramentas não aparecerem nesta conversa, diga-me para abrir uma conversa nova e pedir "chame forgia_estado".',
          '',
          'Os passos 1 e 2 mudam a configuração do agente: é esperado que você me peça permissão para rodar os comandos e editar os arquivos.',
        ].join('\n'),
      codex: (p) =>
        [
          'Instale o servidor MCP do Forgia (o editor 3D aberto neste computador) no Codex e libere as ferramentas dele:',
          '',
          '1. Em ~/.codex/config.toml (crie se não existir), acrescente a seção abaixo; se já houver uma [mcp_servers.forgia], troque só ela. Mantenha todo o resto do arquivo:',
          p.codexToml,
          '',
          '2. default_tools_approval_mode = "auto" libera as ferramentas do forgia sem pedir aprovação. Se a sua versão do Codex recusar essa chave, tire só essa linha e me diga como liberar as ferramentas do servidor forgia na política de aprovação dela.',
          '',
          '3. Confirme: numa sessão nova do Codex, liste as ferramentas forgia_* e chame forgia_estado com o Forgia aberto.',
        ].join('\n'),
      cursor: (p) =>
        [
          'Instale o servidor MCP do Forgia (o editor 3D aberto neste computador) no Cursor:',
          '',
          '1. Em ~/.cursor/mcp.json (crie se não existir), MESCLE em "mcpServers" a entrada abaixo, sem apagar os outros servidores:',
          `"forgia": ${p.cursorJson}`,
          '',
          '2. Permissões: o Cursor pede aprovação antes de usar ferramentas MCP, e isso se libera na interface dele, não num arquivo. Diga-me para abrir Cursor Settings > MCP, conferir que o "forgia" está ligado e, no modo de execução do Agent (Run Mode / auto-run), liberar as ferramentas do forgia ou pô-las na lista de permitidas.',
          '',
          '3. Confirme: numa conversa nova do Agent, liste as ferramentas forgia_* e chame forgia_estado com o Forgia aberto.',
        ].join('\n'),
      generico: (p) =>
        [
          'Servidor MCP "forgia" do Forgia (transporte stdio). Configure no seu cliente de IA:',
          `Comando: ${p.exe}`,
          `Argumento: ${p.script}`,
          `Variáveis de ambiente: ${p.env}`,
          '',
          'No formato "mcpServers" que a maioria dos clientes usa (mescle com o que já existe):',
          p.genericoJson,
          '',
          'Libere as ferramentas do servidor "forgia" (todas começam com forgia_) sem pedir confirmação.',
          'Para conferir: liste as ferramentas forgia_* e chame forgia_estado com o Forgia aberto.',
        ].join('\n'),
    },
  },

  sobre: {
    titulo: 'Sobre o Forgia',
    versao: (v) => `versão ${v}`,
    feito: 'Feito por um carioca — ',
    empresa: 'LarcherTech',
    empresaDe: ', empresa brasileira',
    licenca: 'Licença MIT',
    icones: 'Ícones: Lucide (licença ISC)',
  },

  // mensagens rápidas (toast)
  avisos: {
    modoSoftware: 'Aceleração de vídeo indisponível — o 3D vai funcionar, porém mais lento.',
    nadaExportar: 'Nada para exportar',
    falhaExportar: (msg) => `Falha ao exportar: ${msg}`,
    formatoNaoSuportado: 'Formato não suportado (use .STL, .OBJ ou .3MF)',
    naoLeu: (msg) => `Não foi possível ler o arquivo: ${msg}`,
    semTriangulos: 'O arquivo não tem triângulos',
    modeloGrande: 'Modelo grande: ele não ficará salvo depois que o Forgia for fechado.',
    cruzeiroSemSelecao: 'Selecione uma peça para usar o Cruzeiro.',
    medirBloqueada: 'A peça do ponto final está bloqueada: desbloqueie para movê-la pela régua.',
    medirMesmaPeca: 'Os dois pontos estão na mesma peça: mudar a distância não moveria um em relação ao outro.',
    // desenho que não vira peça (chave = motivo de prepareOutline em src/outline.js)
    desenho: {
      poucos: 'O desenho precisa de pelo menos 3 pontos para virar peça.',
      area: 'O contorno não tem área: desenhe uma forma fechada maior.',
      cruzado: 'O contorno se cruza: desenhe sem cruzar a linha para ele virar peça.',
    },
  },

  erros: {
    // no lugar da vista 3D quando não há WebGL algum
    gpu: {
      titulo: 'O 3D não pôde iniciar neste computador',
      texto: 'Atualize o driver da placa de vídeo e abra o Forgia de novo.',
    },
    // leitor de .3MF: chegam ao usuário depois de avisos.naoLeu
    arquivo3mf: {
      parteAusente: (caminho) => `parte ausente no 3MF: ${caminho}`,
      xmlInvalido: (caminho) => `XML inválido em ${caminho}`,
      aninhados: 'componentes aninhados demais',
      objetoAusente: (id, caminho) => `objeto ${id} não encontrado em ${caminho}`,
      verticeInvalido: 'triângulo com vértice inválido',
    },
  },

  // cartão de dica ao passar o mouse (chave = data-dica)
  dicas: {
    copy: { titulo: 'Copiar', atalho: 'Ctrl+C', texto: 'Copia as formas selecionadas para colar depois.' },
    paste: { titulo: 'Colar', atalho: 'Ctrl+V', texto: 'Cola as formas copiadas, um pouco ao lado das originais.' },
    duplicate: { titulo: 'Duplicar e repetir', atalho: 'Ctrl+D', texto: 'Cria uma cópia no mesmo lugar. Mova ou gire a cópia e aperte de novo: o Forgia repete o mesmo movimento.', video: 'duplicate' },
    delete: { titulo: 'Excluir', atalho: 'Delete', texto: 'Apaga as formas selecionadas. Ctrl+Z traz de volta.' },
    undo: { titulo: 'Desfazer', atalho: 'Ctrl+Z', texto: 'Desfaz a última alteração.' },
    redo: { titulo: 'Refazer', atalho: 'Ctrl+Y', texto: 'Refaz o que foi desfeito.' },
    showAll: { titulo: 'Mostrar tudo', atalho: 'Ctrl+Shift+H', texto: 'Mostra de novo as formas ocultas.' },
    group: { titulo: 'Agrupar', atalho: 'Ctrl+G', texto: 'Junta as formas selecionadas numa peça só. Os furos do grupo recortam os sólidos.', video: 'group' },
    ungroup: { titulo: 'Desagrupar', atalho: 'Ctrl+Shift+G', texto: 'Separa o grupo nas formas originais.' },
    align: { titulo: 'Alinhar', atalho: 'L', texto: 'Mostra pontos para alinhar as formas selecionadas pelo início, pelo centro ou pelo fim de cada eixo.', video: 'align' },
    mirror: { titulo: 'Espelhar', atalho: 'M', texto: 'Mostra setas para espelhar a seleção em cada eixo.', video: 'mirror' },
    draw: { titulo: 'Desenhar', atalho: 'B', texto: 'Desenhe um contorno na mesa, vista de cima: arraste para traçar à mão livre ou clique para pôr pontos na grade. Enter ou o 1º ponto fecha, e o desenho vira uma peça de 2 mm que você ergue pela alça de cima.', video: 'draw' },
    cruise: { titulo: 'Cruzeiro', atalho: 'C', texto: 'Mostra uma bolinha na base da peça selecionada. Arraste por ela e a peça desliza pela superfície das outras, até em faces laterais e inclinadas, alinhada à face. Segure Shift para afundá-la na face, como um furo na parede.', video: 'cruise' },
    measure: { titulo: 'Medir', atalho: 'R', texto: 'Clique em dois pontos para ver a distância e as diferenças em X, Y e Z. Os pontos grudam em vértices, meio de arestas, centro de furos, faces e na grade. Clique no valor e digite outro para mover a peça do ponto final.', video: 'measure' },
    home: { titulo: 'Vista inicial', texto: 'Volta a câmera para a vista padrão da mesa.' },
    fit: { titulo: 'Ajustar à tela', atalho: 'F', texto: 'Enquadra a seleção. Sem seleção, enquadra o projeto inteiro.' },
    in: { titulo: 'Aproximar', texto: 'Aproxima a vista. A roda do mouse também aproxima, na direção do cursor.' },
    out: { titulo: 'Afastar', texto: 'Afasta a vista. A roda do mouse também afasta.' },
    ortho: { titulo: 'Perspectiva ou ortográfica', texto: 'Alterna entre a vista em perspectiva e a ortográfica, sem distorção de profundidade: boa para alinhar e conferir medidas.' },
    novo: { titulo: 'Novo projeto', texto: 'Começa um projeto vazio. Se o atual tiver alterações não salvas, o Forgia pergunta antes se você quer salvá-las.' },
    arquivo: { titulo: 'Arquivo', atalho: 'Ctrl+S', texto: 'Salvar o projeto num arquivo .forgia (Ctrl+S; Ctrl+Shift+S para salvar como), abrir outro (Ctrl+O) e os 5 recentes. O arquivo só muda quando você salva; a cópia de segurança é automática.' },
    abaBiblioteca: { titulo: 'Biblioteca', texto: 'As formas para arrastar até a mesa.' },
    abaObjetos: { titulo: 'Objetos', texto: 'A lista de tudo o que está no projeto, com os grupos e suas partes, inclusive o que está oculto ou bloqueado. Clique para selecionar, use o olho e o cadeado, e dê duplo clique no nome para renomear.' },
    workplane: { titulo: 'Plano de trabalho', atalho: 'P', texto: 'Clique numa face de uma peça, até inclinada: ela vira o chão, com a grade nela. Formas novas, arraste, setas e alças seguem esse plano, e a barra de status mede a partir dele. P de novo volta para a mesa. Não fica salvo no projeto.', video: 'workplane' },
    encaixe: { titulo: 'Criar encaixe', texto: 'Com uma peça selecionada, cria ao lado dela um bloco com o negativo da peça, aberto em cima e com folga (0,25 mm por padrão), para imprimir um soquete ou suporte. O resultado é um grupo editável e um Ctrl+Z desfaz.', video: 'encaixe' },
    categoria: { titulo: 'Categoria da biblioteca', texto: 'Suas criações, Favoritos, Formas básicas, Letras e números, Iniciantes do projeto (peças prontas para editar), Hardware (porcas, parafusos, furos para parafuso e inserto) e Geradores de forma (engrenagem, grade, mola, dobradiça, texto curvo, caixa com tampa).' },
    salvarCriacao: { titulo: 'Salvar seleção como criação', texto: 'Guarda as peças selecionadas como uma forma sua, para arrastar de novo em qualquer projeto. Passe o mouse sobre ela na biblioteca para renomear ou excluir.' },
    listaOcultar: { titulo: 'Ocultar ou mostrar', texto: 'Esconde a peça da vista e da exportação, ou mostra de novo. Numa parte de grupo, esconde só aquela parte. Ctrl+Z desfaz.' },
    listaBloquear: { titulo: 'Bloquear ou desbloquear', texto: 'Trava a peça: ela não se move nem muda de tamanho, nem pela IA, até ser desbloqueada.' },
    credito: { titulo: 'LarcherTech', texto: 'O Forgia é feito pela LarcherTech, empresa brasileira. Abre o site no navegador.' },
    temaEscuro: { titulo: 'Tema escuro', texto: 'Muda a interface e a mesa para o tema escuro. A escolha fica salva.' },
    temaClaro: { titulo: 'Tema claro', texto: 'Muda a interface e a mesa para o tema claro. A escolha fica salva.' },
    bloquear: { titulo: 'Bloquear', atalho: 'Ctrl+L', texto: 'Trava a forma: ela não se move nem muda de tamanho até ser desbloqueada.' },
    desbloquear: { titulo: 'Desbloquear', atalho: 'Ctrl+L', texto: 'Libera a forma para mover e redimensionar.' },
    ocultar: { titulo: 'Ocultar', atalho: 'Ctrl+H', texto: 'Esconde a forma. Mostrar tudo (Ctrl+Shift+H) traz de volta.' },
    soltar: { titulo: 'Soltar na mesa', atalho: 'Shift+D', texto: 'Desce as peças selecionadas até encostarem na mesa, sem mexer no lado. Com o plano de trabalho ligado, elas descem até o plano. Ctrl+Z desfaz.', video: 'soltar' },
    recolher: { titulo: 'Recolher', texto: 'Recolhe o painel e deixa só o nome da forma.' },
    expandir: { titulo: 'Expandir', texto: 'Abre o painel com material e parâmetros.' },
    mark: { titulo: 'Marcar parte', atalho: 'N', texto: 'Clique num ponto da peça para pôr um alfinete numerado. Escreva o que mudar ali e aperte Enter: o pedido, só daquela parte (mesmo dentro de um grupo), é copiado com a imagem para você colar no seu agente de IA.', video: 'mark' },
    limparMarcas: { titulo: 'Limpar marcações', texto: 'Tira todos os alfinetes da vista. As marcações não entram no projeto nem no desfazer.' },
    conectarIA: { titulo: 'Conectar IA', texto: 'Liga um agente de IA ao Forgia. Com o Agent Code integrado, você pede aqui mesmo, em "Pedir à IA". Para Claude, Codex, Cursor e outros, gera o texto para colar no agente: ele instala a ponte do Forgia e passa a criar e alterar peças aqui.' },
    ia_conectada: { titulo: 'IA conectada', texto: 'Um agente de IA usou o Forgia há pouco. Tudo o que ele faz vira um passo de desfazer, e o aviso no canto mostra o que mudou.' },
    pedir: { titulo: 'Pedir à IA', texto: 'Abre a conversa com a IA: escreva o que quer ("faça um chaveiro com o nome ANA") e aperte Enter, e a IA faz a peça aqui no Forgia. No alto da conversa ficam o Marcar, para apontar a parte que vai mudar, e o Conectar IA.', video: 'pedir' },
    ia_pronta: { titulo: 'IA pronta', texto: 'A ponte local está ligada e esperando um agente. Clique para ver como conectar.' },
    ia_desligada: { titulo: 'IA desligada', texto: 'A ponte recusa os pedidos do agente. Ligue em Configurações > IA.' },
    ia_indisponivel: { titulo: 'IA indisponível', texto: 'A ponte local não está disponível neste Forgia. Clique para ver os detalhes.' },
  },
};
